engines:
	eslint:
		enabled: true
	csslint:
		enabled: true

ratings:
	paths:
	- "src/js/**.js"
	- "dist/js/**.js"
	- "dist/css/**.css"

exclude_paths:
- node_modules/**/*
- bower_components/**/*
- dist/**/*
